CREATE TABLE Logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  creation_datetime DATETIME NOT NULL,
  operation VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  log VARCHAR(255),
  PRIMARY KEY (id)
);
